name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]

permissions:
  # to check out code
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

# To use Remote Caching, uncomment the next lines and follow the steps below.
# env:
#  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
#  TURBO_TEAM: ${{ vars.TURBO_TEAM }}

jobs:
  build:
    name: Build
    uses: ./.github/workflows/setup.yml
    with:
      command: build
      command_name: Build # This is the step name in logs

  test:
    name: Test
    uses: ./.github/workflows/setup.yml
    needs: build
    with:
      command: test
      command_name: Test # This is the step name in logs
