on:
  workflow_call:
    inputs:
      command:
        required: true
        type: string
      command_name:
        required: true
        type: string
    secrets:
      TURBO_TOKEN:
        required: false
      TURBO_TEAM:
        required: false

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest

    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

    steps:
      # Checkout code
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      # Setup pnpm
      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      # Setup Node.js
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      # Install dependencies
      - name: Install dependencies
        run: pnpm install

      # Run command (build or test, etc.)
      - name: ${{ inputs.command_name }}
        run: pnpm ${{ inputs.command }}

      # Conditionally upload coverage if this is the test step
      - name: Upload coverage reports to Codecov
        if: ${{ inputs.command == 'test' }}
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
